### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by joaco5121** [aronkahrs-us/inumet-weather-ha#10]
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | America/Montevideo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4828
Installed Version | 1.34.0
Stage | running
Available Repositories | 1410
Downloaded Repositories | 52
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 56.0 GB
disk_used | 16.7 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (17.0.7), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.8.0), Mosquitto broker (6.4.0), Studio Code Server (5.15.0), Jellyfin Server (1.1.4), ESPHome (2023.12.9), Advanced SSH & Web Terminal (17.1.0), Samba share (12.3.0), MPD (1.7.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 30
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 de febrero de 2024, 10:40
-- | --
current_recorder_run | 19 de febrero de 2024, 16:56
estimated_db_size | 104.00 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.15
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 13

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hola, Los departamentos Paysandú. Río Negro, San José y Tacuarembó producen un error al seleccionarlos como opción al intentar agregar la integración a Home Assistant, creo que puede deberse a que llevan tilde, ya que el resto de departamentos funcionan sin problemas.
Agregué la integración a Home Assistant ya que me interesa tener la información sobre las alertas meteorológicas específicamente en Río Negro y San José así que me gustaría poder utilizarla sin problemas. Desde ya, muchas gracias.

### Reproduction steps

1. Agregar la integración a HACS
2. Instalar la Integración
3. Reiniciar Home Assistant
4. Ir a la pagina de integraciones
5. Agregar la integración de INUMET
6. Seleccionar cualquier departamento que incluya un tilde en su nombre

### Debug logs

```text
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inumet/config_flow.py", line 31, in async_step_user
    await self._test_credentials(
  File "/config/custom_components/inumet/config_flow.py", line 68, in _test_credentials
    client = await self.hass.async_add_executor_job(INUMET,station,depto)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/inumet_api/api.py", line 20, in __init__
    self.zone = [x['idInt'] for x in self.zonas() if depto.lower().replace(" ","") in x['deptos']][0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by aronkahrs-us** [comment]
fixed in lastest release
