### ISSUE TITLE
Texto de la alerta metereológica

### ISSUE THREAD

**Issue by nbardier** [aronkahrs-us/inumet-weather-ha#30]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/aronkahrs-us/inumet-weather-ha/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Aparentemente no estaría soportado, con las entidades que genera automáticamente, mostrar el texto de la alerta metereológica

### Describe the solution you'd like

Tener una entidad de texto que muestre el detalle de la alerta

### Describe alternatives you've considered

Ninguna

### Additional context

Sería más informativo tener el texto de la alerta más que una entidad binaria con el estado de la alerta

**Comment by aronkahrs-us** [comment]
La descripción de la alerta está en el sensor binario de la alerta, es un atributo, adjunto una imagen donde se ve
![Screenshot_20240426_143922_Home Assistant.jpg](https://github.com/aronkahrs-us/inumet-weather-ha/assets/85702110/8d38d3c9-2b0c-4b00-abff-e8a041aa12c5)

**Comment by nbardier** [comment]
Sabés que no me sale la descrición, hoy por ejemplo hay alerta, y puse mis coordenadas en el Prado, pero no me da la alerta.
En el log veo esto:

Este error se originó a partir de una integración personalizada.

Logger: custom_components.inumet
Source: custom_components/inumet/binary_sensor.py:101
Integration: Inumet (documentation, issues)
First occurred: 11:15:34 (1 occurrences)
Last logged: 11:15:34

property 'extra_state_attributes' of 'InumetBinarySensor' object has no setter



Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:361
Integration: Clima (documentation, issues)
First occurred: 11:15:34 (1 occurrences)
Last logged: 11:15:34

Error while setting up inumet platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/inumet/weather.py", line 34, in async_setup_entry
    async_add_entities([InumetWeather(coordinator)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 264, in __call__
    instance: PostInit = super().__call__(*args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inumet/weather.py", line 46, in __init__
    self.name = "INUMET"
    ^^^^^^^^^
AttributeError: property 'name' of 'InumetWeather' object has no setter

**Comment by aronkahrs-us** [comment]
Ok, tiene pinta de que es un error de la instalacion de la integracion, probaste borrandola y volviendo a descargarla?

**Comment by nbardier** [comment]
si, probé, ahora me da:

Logger: homeassistant.components.weather
Source: helpers/entity_platform.py:361
Integration: Clima ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 19:36:04 (1 occurrences)
Last logged: 19:36:04
Error while setting up inumet platform for weather

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/inumet/weather.py", line 34, in async_setup_entry
    async_add_entities([InumetWeather(coordinator)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 264, in __call__
    instance: PostInit = super().__call__(*args, **kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/inumet/weather.py", line 46, in __init__
    self.name = "INUMET"
    ^^^^^^^^^
AttributeError: property 'name' of 'InumetWeather' object has no setter


Notar que estoy usando una versión docker de home assistant, usando la última imagen de homeassistant/home-assistant y ésta es la info de mi sistema:

**Comment by nbardier** [comment]
## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.4.17-2136.307.3.6.el8uek.x86_64
arch | x86_64
timezone | America/Montevideo
config_dir | /config

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2 de agosto de 2022, 03:40
-- | --
current_recorder_run | 8 de mayo de 2024, 19:35
estimated_db_size | 10838.10 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.1.0 (9f13219)
-- | --
cloud_online | 3 / 3
local_online | 3 / 3

</details>

**Comment by aronkahrs-us** [comment]
El problema pareciera ser que quiere setear el nombre de la integracion despues de que está seteado y como el nombre es algo que no cambia no tiene definido un setter, lo cual es totalmente logico y no deberia dar problemas, de hecho en todas las instancias que lo probé no dio error, el debug lo hago en una instancia docker.
Pareciera ser un error en asyncio o algo por el estilo. Dejame ver que puedo encontrar, pero a priori, no es un error de la integracion.
